# fly.toml app configuration file generated for vulnerable-app-api on 2023-10-11T20:56:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vulnerable-app-api"
primary_region = "ams"

[build]

[[services]]
  internal_port = 5000
  script = "index.js"  # Specify server.js here

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
